export class NavigationTransition {
  static readonly PUSH_ENTER_MS: number = 520;
  static readonly PUSH_EXIT_MS: number = 300;
  static readonly POP_ENTER_MS: number = 300;
  static readonly POP_EXIT_MS: number = 520;
  static readonly PUSH_ENTER_OPACITY: number = 1;
  static readonly PUSH_EXIT_OPACITY: number = 0.72;
  static readonly POP_ENTER_OPACITY: number = 1;
  static readonly POP_EXIT_OPACITY: number = 1;
}
